<?php
return array(
	'adj','as','ain\'t','and','any','are','aren\'t', 'about', 'an',
	'a\'s','but','by','can','cannot','cant','can\'t','c\'mon','co.','com', 'contact',
	'could','couldn\'t','c\'s','dare','daren\'t','did','didn\'t','does','doesn\'t','doing','done','don\'t',
	'each','edu','else','elsewhere','etc','for','find','had','hadn\'t','has','hasn\'t',
	'have','haven\'t','having','he\'d','he\'ll','her','here','hers','herself','he\'s','him','himself',
	'his','hither','i\'d','i\'ll','i\'m','inc','inc.','is','in','isn\'t','it','it\'d','it\'ll','its','it\'s','itself','i\'ve',
	'let','let\'s','ltd','many','me','may','mayn\'t','mrs','much','must','mustn\'t', 'my',
	'needn\'t','non','not','off', 'on', 'of', 'or', 'okay','once','one','ones','one\'s','other','others','our','ours','out','outside','over','per',
	'rather','saw','say','saying','says','shall','shan\'t','she','she\'d','she\'ll','she\'s',
	'should','shouldn\'t','six','still','sub','such','sup','than','that', 'to',
	'that\'ll','thats','that\'s','that\'ve','the','their','theirs',
	'then','thence','there','thereafter','thereby','there\'d','therefore',
	'there\'ll','there\'re','theres','there\'s','there\'ve','these','they',
	'they\'d','they\'ll','they\'re','they\'ve','thing','things','think','third','thirty',
	'this','those','though','three','through','throughout','thru',
	'thus','till','too','t\'s','upon','use','was','wasn\'t','way','we\'d',
	'well','we\'ll','went','were','we\'re','weren\'t','we\'ve','what',
	'whatever','what\'ll','what\'s','what\'ve','when','whence','whenever','where',
	'whereafter','whereas','whereby','wherein','where\'s','whereupon','wherever',
	'whether','which','whichever','while','whilst','whither','who','who\'d','whoever',
	'whole','who\'ll','whom','whomever','who\'s','whose','why','will',
	'with','within','without','wonder','won\'t','would','wouldn\'t','yes','yet',
	'you','you\'d','you\'ll','your','you\'re','yours','yourself','yourselves','you\'ve',
	'arse', 'asshole', 'asswipe', 'bitch', 'bollocks', 'bugger', 'bullshit', 'cock tease', 'cunt', 'ergi', 'faggot', 'fuck',
	'sexual', 'honky', 'motherfucker', 'motherfuck', 'nigga', 'nigger', 'pussy', 'shit', 'twat', 'wanker', 
);