<?php
return array(
	'agg','come','e','qualsiasi','sono','non sono', 'circa', 'un',
	'ma','da','puo','non puo','dai','com', 'contatto',
	'potrebbe','non potrebbe','provocare','non provocare','fatto',
	'ogni','edu','altro','altrove','etc','per','trova','avuto','non ha avuto','ha','non ha',
	'ha','non hanno','avendo','avra','suo','qui','lui stesso','e','se stesso',
	'qui','ho','avro','sono','in','non e','esso','esso stesso',
	'fare','sia','societa','molti','me','dovrebbe','non dovrebbe','sig','molto','deve','non deve', 'mio',
	'non necessario','non','spento', 'acceso', 'di', 'o', 'okay','una volta','uno','altro','altri','nostro','nostri','fuori','esterno','oltre','per',
	'piuttosto','detto','dice','dicendo','si potrebbe','lei','lei e',
	'dovrebbe','non dovrebbe','sei','ancora','sotto','tale','sup','di','quello', 'verso',
	'sara','avra','il','loro','allora','percio','la','successivamente','in tal modo','quindi','essi',
	'essi dovrebbero','essi vorrebbero','essi sono','essi hanno','cosa','cose','pensa','terzo',
	'questo','quelli','pensiero','albero','attraverso',
	'cosi','fino','anche','fino a','usa','era','non era','modo','noi dovremmo',
	'bene','faremo','andati','siamo','non eravamo','cosa',
	'qualsiasi','dove','quando vuoi',
	'dopodiche','ovunque', 'te', 'si', 'noi', 'non',
	'se','cui','chiunque','mentre','durante','dove','chi','chi vorrebbe','chi mai',
	'intero','chi vorra','di cui','chiunque','chi e','il cui','perche','vorra',
	'con','entro','senza','volere','non voglio','vorrei','non vorrei','si','ancora',
	'tu','dovresti','vorrai','tuo','sei','tuo','te stesso','voi stessi','hai',
	'culo', 'stronzo', 'puttana', 'cazzate', 'piccolo bastardo', 'stronzate', 'figa di legno', 'stronza', 'culattone', 'frocio', 'cazzo',
	'sessuale', 'squallido', 'bastardo', 'negro', 'figa', 'merda', 'topa', 'coglione','segaiolo','mezzasega', 'pirla','faccia di culo','testa di cazzo',
);