<?php
return array(
	'och', 'att', 'det', 'som', 'för', 'med', 'till', 'den', 'har', 'här', 'inte', 'ett', 'han', 'hon', 
	'men', 'var', 'jag', 'sig', 'från', 'kan', 'man', 'när', 'säger', 'under','också', 'efter', 'eller', 'sin', 
	'där', 'vid', 'mot', 'ska', 'skulle', 'kommer', 'får', 'finns' ,'vara', 'hade', 'alla', 'andra', 
	'mycket', 'sedan', 'över', 'bara', 'blir', 'upp', 'även', 'vad', 'två', 'vill', 'många', 'hur', 'mer',
	'går', 'detta', 'nya', 'skall', 'hans', 'utan', 'sina', 'något', 'allt', 'första', 'fick', 'måste',
	'mellan', 'blev', 'bli', 'dag', 'någon', 'några', 'sitt', 'stora', 'varit', 'dem', 'bland', 'bra',
	'tre', 'genom', 'del', 'hela', 'annat', 'fram', 'gör', 'ingen', 'göra', 'enligt', 'mig', 'redan',
	'inom', 'kom', 'helt', 'samma', 'kanske', 'själv', 'oss', 'tidigare', 'dock', 'denna', 'både', 'tid', 
	'kunna', 'fått', 'stor', 'olika', 'ser', 'flera', 'plats', 'kunde', 'gäller', 'honom', 'aldrig', 'barn', 
	'varje', 'lite', 'sätt', 'just', 'väl', 'tar', 'mest', 'per', 'står', 'fem', 'tror', 'rätt', 'dessa',
	'gång', 'därför', 'fyra', 'ny', 'gick', 'hos', 'dessutom', 'ger', 'lika', 'eftersom', 'vilket', 
	'trots', 'tycker', 'människor', 'ligger', 'vet', 'kvar', 'bättre', 'gjorde', 'ändå', 'inför', 'senaste',
	'samtidigt', 'annan', 'ännu', 'blivit', 'fall', 'talet', 'exempel', 'gamla', 'deras', 'tiden', 'min', 
	'hennes', 'sista', 'komma', 'större', 'visar', 'senare', 'tog', 'nästa', 'ge', 'mindre', 'gjort', 'innan',
	'alltid', 'pengar', 'sade', 'först', 'stället', 'vår', 'före', 'tillbaka', 'ner', 'nog', 'samt', 'ofta',
	'själva', 'inget', 'fler', 'säga', 'egen', 'igen', 'runt', 'nästan', 'lopp', 'förra', 'året', 'mål',
	'längre', 'svårt', 'bästa', 'länge', 'stort', 'enda', 'liv', 'fortfarande', 'medan', 'bakom',
	'haft', 'minst', 'fast', 'början',  'alltså', 'bort', 'varför', 'anser', 'våra', 'mitt', 'dess', 'nytt', 
	'tio', 'inga', 'fanns', 'egna', 'utanför', 'ville', 'långt', 'framför', 'båda', 'behöver', 'par', 'nej', 
	'största', 'direkt', 'folk', 'borde', 'väg', 'klart', 'göran', 'bör', 'vidare', 'menar', 'håller', 'lätt', 
	'ytterligare', 'hem', 'gått', 'flesta', 'särskilt', 'därmed', 'cirka', 'heller', 'gången', 'åren', 
	'började', 'däremot', 'sett', 'henne', 'kring', 'känner', 'liten', 'börjar', 'vilka', 'sidan', 'riktigt',
	'små', 'vissa', 'såg', 'slut', 'ned', 'hålla', 'drygt', 'emot', 'nära', 'gav', 'fel', 'tagit', 'namn', 
	'liksom', 'sådan', 'vilken', 'års', 'ganska', 'vem', 'ens', 'visst', 'all', 'frågor', 'verkligen', 'hög', 
	'vårt', 'stod', 'ord', 'visa', 'eget', 'tycks', 'annars', 'stå', 'rad', 'förstås',
);